### ISSUE TITLE
Collectionview and tableview

### ISSUE THREAD

**Issue by Michele404** [eBay/HeadGazeLib#3]
How can I adapt this code for tableview and collectionview?

**Comment by stonexjr** [comment]
Please see [sample code](https://github.com/eBay/HeadGazeLib/blob/master/examples/HeadSwipe/HeadSwipe/MainViewController.swift#L82-L131) in MainViewController on how to adapt the code for [DealGallery](https://github.com/eBay/HeadGazeLib/blob/master/examples/HeadSwipe/HeadSwipe/DealGallery.swift)(UITableView) and [DealRow](https://github.com/eBay/HeadGazeLib/blob/master/examples/HeadSwipe/HeadSwipe/DealRow.swift#L16)(UICollectionView)
