### ISSUE TITLE
Hide button does not disable headgaze!

### ISSUE THREAD

**Issue by nbawe** [eBay/HeadGazeLib#4]
Hello!

When hiding button:
myButton.isHidden = true

HeadGaze still recognizes touch.

How to overcome this?

**Comment by nbawe** [comment]
Solved with constraints! The problem was in the button frame size!

**Comment by stonexjr** [comment]
Setting `isHidden` to `true` does not stop the sensor from tracking your head motion which is not power efficient. The [GIF](https://github.com/eBay/HeadGazeLib/tree/master/examples/demo) demo shows that it is possible to disable the head tracking, hence all the UI widgets fall back to the conventional. It is achieved by temporarily removing the member variable `virtualCursorView` from the superview of type `UIHeadGazeViewController`. Example code can be found in the code block [here](https://github.com/eBay/HeadGazeLib/blob/master/examples/demo/demo/ViewController.swift#L29-L48)
